# Generated by Django 3.1.7 on 2021-03-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210320_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.IntegerField(),
        ),
    ]
