# Generated by Django 3.1.7 on 2021-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210320_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Android'), (2, 'Java'), (3, 'Kotlin')], verbose_name='Language_Type'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
