# Generated by Django 3.1.7 on 2021-03-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210320_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.type'),
        ),
    ]
